CREATE DATABASE IF NOT EXISTS smartmeal;
USE smartmeal;

CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  cpf VARCHAR(14) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL,
  telefone VARCHAR(20),
  senha VARCHAR(255) DEFAULT NULL
);

select * from usuarios;